### ISSUE TITLE
Functionality issue: choosing answers

### ISSUE THREAD

**Issue by Becky449** [Becky449/quiz-mania#8]
When an answer is picked, the user cannot be able to repick the answer for the next question as the button remains marked.
-when the correct answer is picked, a new error occurs
- Scoring not working
- End of question does not prompt for the conclusive score anymire

**Comment by Becky449** [comment]
The error: 
Cannot destructure property 'prompt' of 'question' as it is undefined.
TypeError: Cannot destructure property 'prompt' of 'question' as it is undefined.
    at Question (http://localhost:3000/static/js/bundle.js:125:5)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:20417:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:23297:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:25009:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:10013:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:10057:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:10114:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:29978:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:29226:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:29149:9)
ERROR
